### ISSUE TITLE
fbtr64toolbox.tar.bz2 should be plain text

### ISSUE THREAD

**Issue by fiwswe** [MarcusRoeckrath/fbtr64toolbox#5]
Using GitHub to serve a compressed archive is pretty useless.

Why not place the content files of the archive here? That way people can view them, comment on details, file issues and PRs, etc.

You can still tag versions for defined releases if that was your reason for using the archive.

**Comment by MarcusRoeckrath** [comment]
Hello,

Am Mittwoch, 23. August 2023 00:41 schrieb fiwswe:

> Using GitHub to serve a compressed archive is pretty useless.
>
> Why not place the content files of the archive here? That way people can
> view them, comment on details, file issues and PRs, etc.
>
> You can still tag versions for defined releases if that was your reason
> for using the archive.

Development of this tool is done for the the server distribution eisfair. 
eisfair uses tar for installation but contains some special files useless 
on every other distribution.

For years there was no distribution for other distris; people who heard of 
the tool downloaded the eisfair installtion package or asked me for the 
script personally.

Mirko Dölle from c't asked me to put the package somewhere for download 
outside the eisfair package server because he wanted to give a hint and 
url to the script in his article.

It was a quick solution to use my existing github account to establish a 
download opportunity for everyone and not to establish a central 
development point for this tool.

Around the complete archiv i put the changes and the document file directly 
to github so taht everyone could see whats the script is for.

Maybe I will change this in the future, please download the full archive 
for now.

-- 
Gruß Marcus

**Comment by fiwswe** [comment]
Ok, thanks for the explanation.
