### ISSUE TITLE
Port can be created but no longer deleted

### ISSUE THREAD

**Issue by caco3** [MarcusRoeckrath/fbtr64toolbox#7]
Thanks for this great script!

I use it since years to automatically create a port 80 forwarding for letsencrypt and to remove it again afterwards.

A while ago I got a new Fritzbox. And It causes some issues (or maybe they are related to the FritzOS, I don't know).
I successfully can create a new port forwarding with the script using `./fbtr64toolbox.sh add --extport 80 --protocol TCP --intclient 192.168.1.2 --intport 80 --description "LetsEncrypt" --active` and it shows up correctly in the Web UI and works as expected.
How ever, the script is unable to delete it again afterwards. This has always worked with `./fbtr64toolbox.sh del --description "LetsEncrypt"`. But now it simply fails silently.

Until now I used the script version `2.3.1` but I now also tested it with the latest `3.3.7`.

The new Fritzbox (where I have the issue) is a "FRITZ!Box 5530 Fiber", the old one (where it worked fine) was a "FRITZ!Box 7490".

The new script shows this:

```bash
> ./btr64toolbox.sh add --extport 80 --protocol TCP --intclient 192.168.1.99 --intport 80 --description "LetsEncrypt" --active

Add port forwarding (FRITZ!Box 5530 Fiber Release 257.07.81@192.168.1.1)
```

```bash
> ./fbtr64toolbox.sh del --description "LetsEncrypt" --verbose
Delete port forwarding (FRITZ!Box 5530 Fiber Release 257.07.81@192.168.1.1)

Return codes of TR-064 function calls
tr64desc.xml;deviceinfo;DeviceInfo:1;GetSecurityPort: ok
tr64desc.xml;deviceinfo;DeviceInfo:1;GetInfo: ok
tr64desc.xml;wanpppconn1;WANPPPConnection:1;GetInfo: ok
tr64desc.xml;wanpppconn1;WANPPPConnection:1;DeletePortMapping: 714 NoSuchEntryInArray
---------------------------------------------------------------------------------
Device        : FRITZ!Box 5530 Fiber Release 257.07.81@192.168.1.1
Command line  : del --description LetsEncrypt --verbose
Auth method   : user/password
Script version: 3.3.7
Errorlevel    : 0
Errorcode     : Success
---------------------------------------------------------------------------------

```

```bash
> .fbtr64toolbox.sh show
Port forwardings (FRITZ!Box 5530 Fiber Release 257.07.81@192.168.1.1)
Port forwardings set by authorized users
Idx Act Description               Host IP:Port        Pro Client IP:Port        
  [..]
 10 yes LetsEncrypt               0.0.0.0:80          TCP 192.168.1.2:80       

Port forwardings set by any user/device via upnp
```

If I try to disable the port forwarding instead, I get following error:
```bash
> ./fbtr64toolbox.sh disable --description "LetsEncrypt" --verbose
Disable port forwarding (FRITZ!Box 5530 Fiber Release 257.07.81@192.168.1.1)
Error on communication with fritzbox

Return codes of TR-064 function calls
tr64desc.xml;deviceinfo;DeviceInfo:1;GetSecurityPort: ok
tr64desc.xml;deviceinfo;DeviceInfo:1;GetInfo: ok
tr64desc.xml;wanpppconn1;WANPPPConnection:1;GetInfo: ok
tr64desc.xml;wanpppconn1;WANPPPConnection:1;AddPortMapping: 600 Argument Value Invalid
---------------------------------------------------------------------------------
Device        : FRITZ!Box 5530 Fiber Release 257.07.81@192.168.1.1
Command line  : disable --description LetsEncrypt --verbose
Auth method   : user/password
Script version: 3.3.7
Errorlevel    : 1
Errorcode     : Error on communication with fritzbox
---------------------------------------------------------------------------------
```

**Comment by MarcusRoeckrath** [comment]
Hi,

Am Mittwoch, 28. August 2024, 15:11:39 schrieb CaCO3:

> Thanks for this great script!

:-)))))

> I use it since years to automatically create a port 80 forwarding for
> letsencrypt and to remove it again afterwards.

That was the initial reason to start the development of the script.

> A while ago I got a new Fritzbox. And It causes some issues (or maybe they
> are related to the FritzOS, I don't know). I successfully can create a new
> port forwarding with the script using `./fbtr64toolbox.sh add --extport 80
> --protocol TCP --intclient 192.168.1.2 --intport 80 --description
> "LetsEncrypt" --active` and it shows up correctly in the Web UI and works
> as expected. How ever, the script is unable to delete it again afterwards.
> This has always worked with `./fbtr64toolbox.sh del --description
> "LetsEncrypt"`. But now it simply fails silently.

Thats known and is described in the documentation in german language:

"Das Loeschen von Portfreigaben mittels del-Kommando scheint ab Firmware 7.25
nicht mehr korekt zu funktionieren. Die Fritzbox signalisiert zwar eine
erfolgreiche Ausfuehrung des Kommandos, jedoch wird die Freigabe weiterhin
angezeigt (show-Kommando) und auch in der Weboberflaeche wird sie aufgefuehrt.
Eine nochmalige Ausfuehrung des del-Kommandos wird mit der Fehlermeldung 
quittiert, dass die Freigabe nicht existiere und sie wird weiterhin gelistet. 
Zudem bleibt sie weiterhin aktiv, bis sie in der Weboberflaeche der Fritzbox 
geloescht wird."

Your do not understand german? Let my try to translate a summary of this 
paragraph:

"The deletion of port forwardings seams not working since fritzbox firmware 
7.25. The fritzbox confirms that the function worked correct but the port 
forwarding is furthermore shown in the WebGUI of the fritzbox. Another call of 
the del command will print an error message. The port forwarding remains 
active until deleted in the WebGUI."

I was aware of this change, when my both 7490 gots the firmware update 7.2.5 
and was confirmed by other users.
 
> > ./btr64toolbox.sh add --extport 80 --protocol TCP --intclient 192.168.1.99
> > --intport 80 --description "LetsEncrypt" --active

> Add port forwarding (FRITZ!Box 5530 Fiber Release ***@***.***)
> ```
> Errorcode     : Success

> > .fbtr64toolbox.sh show
> 
> Port forwardings (FRITZ!Box 5530 Fiber Release ***@***.***)
> Port forwardings set by authorized users
> Idx Act Description               Host IP:Port        Pro Client IP:Port
>   [..]
>  10 yes LetsEncrypt               0.0.0.0:80          TCP 192.168.1.2:80
> 
> Port forwardings set by any user/device via upnp

Port forwardings remains active and wasn't deleted.

> If I try to disable the port forwarding instead, I get following error:
> ```bash
> 
> > ./fbtr64toolbox.sh disable --description "LetsEncrypt" --verbose
> 
> Disable port forwarding (FRITZ!Box 5530 Fiber Release ***@***.***)
> Error on communication with fritzbox
> 
> Return codes of TR-064 function calls
> tr64desc.xml;deviceinfo;DeviceInfo:1;GetSecurityPort: ok
> tr64desc.xml;deviceinfo;DeviceInfo:1;GetInfo: ok
> tr64desc.xml;wanpppconn1;WANPPPConnection:1;GetInfo: ok
> tr64desc.xml;wanpppconn1;WANPPPConnection:1;AddPortMapping: 600 Argument
> Value Invalid
> ---------------------------------------------------------------------------
> ------ Device        : FRITZ!Box 5530 Fiber Release ***@***.***
> Command line  : disable --description LetsEncrypt --verbose
> Auth method   : user/password
> Script version: 3.3.7
> Errorlevel    : 1
> Errorcode     : Error on communication with fritzbox
> ----------------------------------------------------------------------------

The disable/enable commands expects a full command line like add where --
inactive/--active is set by default.

The disable commands does not delete a port forward it adds a port forward but 
sets the port forward to inactive.

add, disable and enable alters the state of a port forwarding if existing on 
the fritzbox.

If you does not give all command line parameters the missing are taken from 
the script configuration file; are these values the same as needed for this 
special port forwarding.

What is written down in the configuration file for this values:

new_remote_host
new_external_port
new_protocol
new_internal_port
new_internal_client

Should be

new_remote_host=""
new_external_port="80"
new_protocol="TCP"
new_internal_port="80"
new_internal_client="192.168.1.99"
new_port_mapping_description="LetsEncrypt"

in your case because missing command line parameters are taken from the 
configuration file.

Because deletion does not work on newer firmwares try to set the port 
forwarding inactive:

./btr64toolbox.sh add --extport 80 --protocol TCP --intclient 192.168.1.99
--intport 80 --description "LetsEncrypt" --inactive

or

./btr64toolbox.sh disable --extport 80 --protocol TCP --intclient 192.168.1.99
--intport 80 --description "LetsEncrypt"

For next certificate renewing activate the port forwarding again:

./btr64toolbox.sh add --extport 80 --protocol TCP --intclient 192.168.1.99
--intport 80 --description "LetsEncrypt" --active

or

./btr64toolbox.sh enable --extport 80 --protocol TCP --intclient 192.168.1.99
--intport 80 --description "LetsEncrypt"

-- 
Gruß Marcus

**Comment by MarcusRoeckrath** [comment]
Hi,

one addition to the add (enable, disable) commands:

If a existing port forward should be changed only

intport
description
status (active/inactive)

can differ from the port forward stored in the fritzbox and will lead to change these settings of an existing port forward.

extport, protocol and intclient has to be the same.

If these conditions are not apply the fritzbox will report and error or will add a new port forwarding.

**Comment by caco3** [comment]
> That was the initial reason to start the development of the script.

:) Nice to not be the only one with that need.

German is fine for me, I am from Switzerland. But I prefer to use English so non-German speakers can also understand it.

And I am really sorry to have missed your explanation in the documentation. I only checked the script and the Github readme :(

And thanks for the examples, they work as needed.

**Comment by caco3** [comment]
A suggestion:
Since the script fetches the OS version version on each call, why not show a warning if a Fritzbox with the broken version is used?

**Comment by MarcusRoeckrath** [comment]
Hi,

Am Donnerstag, 29. August 2024, 12:07:09 schrieb CaCO3:

> > That was the initial reason to start the development of the script.
> :
> :) Nice to not be the only one with that need.

It was exactly the same reason you are using the script: temporarily creating 
a port forward for letsencrypt certificate actualisation.

From these start point the script was growing and growing.
 
> And I am really sorry to have missed your explanation in the documentation.
> I only checked the script and the Github readme :(

No problem.

> And thanks for the examples, they work as needed.

ok, so the problem should be solved unless avm will make more changes in the 
firmware.

-- 
Gruß Marcus

**Comment by MarcusRoeckrath** [comment]
Hi,

Am Donnerstag, 29. August 2024, 12:19:34 schrieb CaCO3:

> A suggestion:
> Since the script fetches the OS version version on each call, why not show a
> warning if a Fritzbox with the broken version is used?

I do not have any official information which functions were changed, added or 
removed in which firmware version on what fritzbox.

Therefor I do not want to "cry out" features because I'm not avm or associated 
with them.

It's not a good idea to propagate facts of the technicalsite of fritzboxes 
depending only on some own experience.

AVM; does not support developers like me with any infos.

-- 
Gruß Marcus
